name: Release Drafter

on:
  push:
    branches: [develop, main]
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  update-release-draft:
    name: Update Release Draft
    runs-on: ubuntu-latest
    steps:
      - uses: release-drafter/release-drafter@eada3c96a64734dd381cfbda23511034e328ddb0 # v7.6.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
